args <- commandArgs(trailingOnly = TRUE)
input <- paste(args[1],args[2],sep="/")
data <-read.table(file=input)
out <- paste(args[1],"group_sizes.jpeg",sep="/")
jpeg(out)
hist(data$V1,xlab="Group size(# read pairs)",main="Number of Read Pairs for all Group",nclass=500)
dev.off()